#ifndef TEXT_KEYS_AND_LANGUAGES_HPP
#define TEXT_KEYS_AND_LANGUAGES_HPP

typedef enum {
	PL,
	GB,
	NUMBER_OF_LANGUAGES,
} LANGUAGES;

typedef enum {
	T_CZESC,
	T_MAM_NA_IMIE,
	T_POCHODZE_Z,
	T_TEKST_NA_DWIE_LINIE,
	T_KEYS,
	T_ENTEREDTEXTKEYS,
	T_ENTEREDTEXT,
	T_NUMMODE,
	T_ALPHAMODE,
	T_DODAJ_POKOJ,
	T_DOM,
	T_MIESZKANIE,
	T_DODAJ_URZADZENIE,
} TEXTS;

#endif /* TEXT_KEYS_AND_LANGUAGES_HPP */
